spring.application.name=product-service
app.jwt.secret=abishek-super-secret-key-must-be-32-chars-minimum-for-hs256
app.jwt.expiration=86400000
logging.level.org.springframework.boot.autoconfigure=DEBUG
app.product.max-page=20
app.product.default-currency=INR
app.product.cache-enabled=true
app.audit.enabled=true