spring.application.name=product-service
app.jwt.secret=abishek-super-secret-key-must-be-32-chars-minimum-for-hs256
app.jwt.expiration=86400000
logging.level.org.springframework.boot.autoconfigure=DEBUG
app.product.max-page=20
app.product.default-currency=INR
app.product.cache-enabled=true
app.audit.enabled=true
management.endpoints.web.exposure.include=*
management.endpoint.health.show-details=always
management.info.env.enabled=true
info.app.name=Product Service
info.app.version=1.0.0
info.app.developer=Abishek
info.app.description=Spring Boot microservice demo

spring.datasource.url=jdbc:postgresql://ep-old-fog-aotexbmn.c-2.ap-southeast-1.aws.neon.tech/neondb?sslmode=require
spring.datasource.username=neondb_owner
spring.datasource.password=npg_MVs8jb3kzEGS
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=create-drop
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect